language: python

install:
  - pip install tox coveralls

script:
  - coverage erase
  - tox

after_success:
  - coverage combine
  - coverage report
  - coveralls

notifications:
  email:
    - sinkler@sinkler.ru
